spring:
  application:
    name: aram
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/aram?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: topsecret

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /swagger/api
    groups-order: DESC
    tags-sorter: alpha

